const input = {
  Header: { function: "D", termtype: "HTS", trcode: "1143" },
  Input1: {
    szMemberNo: "", //회원사,
    nCourse_Idx: "", //계약코스 순번,
  },
};

const outputOneInKor = [
  "szResult",
  "상품구분",
  "계좌구분",
  "계좌상태",
  "메모",
  "기본마진",
  "오버나잇 여부",
  "오버나잇 승수",
  "오버위크엔드 승수",
  "레벨 여부",
  "1단계계약수 시작",
  "1단계계약수 끝",
  "1단계계약승수",
  "2단계계약수 시작",
  "2단계계약수 끝",
  "2단계계약승수",
  "3단계계약수 시작",
  "3단계계약수 끝",
  "3단계계약승수",
  "마진콜 타입",
  "마진콜경고1",
  "마진콜경고2",
  "마진콜경고3",
  "주문증거금",
  "유지증거금",
  "최소예치금",
  "수수료(출금)",
  "수수료(송금)",
  "수수료(매수)",
  "수수료(매도)",
  "이자형태",
  "알림수준",
  "에러오류위치",
  "메세지",
  "정상처리여부",
  "거래방법",
  "롤오버 부과방식",
  "데이트레이더구분",
];

const outputOneInEng = [
  "szTradeType",
  "cAcc_Type",
  "cAcc_Cond",
  "szFX_Memo",
  "szBase_Mg",
  "cON_YN",
  "szON_Mul",
  "cOW_YN",
  "szOW_Mul",
  "cLv_YN",
  "szLv1_PosSu_St",
  "szLv1_PosSu_Ed",
  "szLv1_Pos_Mul",
  "szLv2_PosSu_St",
  "szLv2_PosSu_Ed",
  "szLv2_Pos_Mul",
  "szLv3_PosSu_St",
  "szLv3_PosSu_Ed",
  "szLv3_Pos_Mul",
  "cMcall_Type",
  "szMcall_Lv1",
  "szMcall_Lv2",
  "szMcall_Lv3",
  "szOrder_Mg_M",
  "szMnt_Mg_M",
  "szMin_Depo_M",
  "fCommision",
  "fRover_Fee",
  "fOpen_Markup",
  "fClose_Markup",
  "cInterest_Type",
  "szNotify_Level",
  "szErrPlace",
  "szMessage",
  "szReturn",
  "cTrade_Div",
  "cRover_Su",
  "cDayTradeCM",
];
